ElizabethThorner/FrontEndRebabel

.github/workflows/publish_gap_app.yml

We need a yaml file in the .github/workflows folder in the default branch(main) to start using GitHub Actions. This PR adds that minimal workflow.

Create minimal workflow in .github/workflows folder

---

src/Components/App.jsx
src/main.js
src/preload.js

Creates select file functionality for single file

Creates Select File Functionality

---

src/Components/App.jsx

Gets the user selected values from the input and output file type selects.

Add Input types functionality

---

.gitignore
src/Components/About.jsx
src/Components/App.jsx
src/Components/Help.jsx
src/assets/styles.css

text and functionality implemented, design still work in progress

create help and about modals

---

src/Components/AdditionalSettings.jsx
src/Components/App.jsx
src/assets/styles.css
src/main.js

Add the additional settings component with some basic functionality.

Add Additional Settings Component

---

src/Components/App.jsx
src/assets/styles.css
src/main.js
src/preload.js

Passes data to main.js and creates loading spinner

Adds Some convert functionality and loading spinner

---

src/Components/App.jsx
src/assets/styles.css
src/main.js

Adds basic multiple files input and displays in the form.

Multiple File Input

---

src/Components/App.jsx
src/Components/Mappings.jsx

Currently just a text field, but may change

Adds Mappings Button

---

src/main.js

Adds a SaveAs dialog that populates it within a default file name with the output type extension.

Creates SaveAs functionality

---

src/Components/App.jsx
src/Components/NLPConfig.jsx
src/assets/styles.css

Adds functionality for nlp input where user can select combined which includes the delimiter or separated which includes the part of speech and language file.

Adds NLP selection component

---

rebabel_scripts/rebabel_convert.py

you will need to remake the rebabel_convert executable

added a line that fixes nlp single file uploads

---

src/Components/App.jsx
src/Components/Mappings.jsx
src/assets/styles.css
src/main.js

Adds in type, out type, in feature, and out feature to mappings and updates the state.

Add forms and functionality to mappings component

---

src/main.js

stringify line added

---

src/Components/App.jsx
src/Components/SelectFiles.jsx
src/Components/SelectFiles.module.css
src/assets/styles.css

Move the Select File into its own component.

Refactor Select File

---

src/Components/App.jsx
src/Components/Convert.jsx
src/Components/Convert.module.css
src/assets/styles.css

Took the convert code and moved it into its own component.

Refactor Convert

---

forge.config.js
rebabel_scripts/rebabel_convert.py
src/main.js

The Gap App application will no longer hang during file conversion. The conversion will terminate and the output file will be produced.

Resolve Gap App hanging during file conversion process

---

src/Components/App.jsx
src/Components/Convert.jsx
src/Components/Errors.jsx
src/Components/Errors.module.css
src/Components/SelectFiles.jsx
src/Components/SelectFiles.module.css
src/ErrorStates.js
src/assets/styles.css

Add errors for selecting duplicate file names and trying to convert with no files selected.

Add Select File Errors

---

src/main.js
src/menu.js

add developer tools to view menu if not packaged

add developer tools to view menu if not packaged

---

src/main.js

remove duplicate isDev line

---

src/main.js

in case app crashed and database wasn't cleared

clear database on app startup

---

src/Components/App.jsx
src/Components/Convert.jsx
src/Components/Convert.module.css
src/Components/Error.module.css
src/Components/NLPConfig.jsx
src/Components/NLPConfig.module.css
src/Components/OutputFileConfig.jsx
src/Components/SelectFiles.jsx
src/Components/SelectFiles.module.css
src/Components/SelectTypes.jsx
src/Components/SelectTypes.module.css
src/ErrorStates.js
src/assets/styles.css
src/main.js

Add more error catching to the UI.

Add more error catching

---

src/assets/styles.css
src/main.js

Allows the window to be maximized and adjusts the container size for the content.

Enable Maximization of Window

---

src/Components/App.jsx
src/Components/Chip.jsx
src/Components/Convert.jsx
src/Components/OutputConfigs/ElanConfig.jsx
src/Components/OutputConfigs/ElanConfig.module.css
src/Components/SelectFiles.jsx
src/assets/styles.css

Added a css chip for file select and removal and some error messaging.

Update Elan modal UI

---

src/Components/OutputConfigs/ElanConfig.jsx
src/Components/SelectFiles.jsx

Disables the browse button when selecting a file so multiple select file dialogs don't occur.

Disables Browse button when Selecting File

---

src/Components/SelectTypes.jsx
src/Components/SelectTypes.module.css

Minor UI update that adds more spacing for the types error message and input/output config buttons

Updates the UI

---

src/Components/SelectFiles.jsx
src/main.js

Added multifile select to the main file selection so someone can upload more than one at a time. Single select is still an option.

Add Multifile Select

---

src/HelpDocumentation/About/app.js
src/HelpDocumentation/About/index.html
src/HelpDocumentation/Help/exporting.html
src/HelpDocumentation/Help/getting-started.html
src/HelpDocumentation/Help/importing.html
src/HelpDocumentation/Help/index.html
src/HelpDocumentation/Help/mappings.html
src/HelpDocumentation/helpDocumentation.css
src/main.js
src/menu.js
src/preload.js

reduce menu bar clutter, resize windows

Rework about

---

test/specs/test.e2e.mjs

Add more Jasmine tests to validate expected elements and functionality of reBabel application
